import { StoredFileType } from "@/types/file";

export const getFileType = (mimeType: string): StoredFileType => {
  const types: Record<string, StoredFileType> = {
    "application/pdf": "PDF",
    "text/plain": "TXT",
    "text/csv": "CSV",
    "application/json": "JSON",
    "application/xml": "XML",
    "text/xml": "XML",
    "text/markdown": "MD",
    "text/rtf": "RTF",
    "application/rtf": "RTF",
    "application/msword": "DOC",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
      "DOCX",
    "application/vnd.ms-excel": "XLS",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
      "XLSX",
    "application/vnd.ms-powerpoint": "PPT",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation":
      "PPTX",
    "application/zip": "ZIP",
    "application/x-zip-compressed": "ZIP",
    "application/x-rar-compressed": "RAR",
    "application/vnd.rar": "RAR",
    "application/x-7z-compressed": "7Z",
    "application/x-tar": "TAR",
    "application/gzip": "GZ",
    "application/x-gzip": "GZ",
    "application/x-bzip2": "BZ2",
    "image/jpeg": "JPEG",
    "image/jpg": "JPG",
    "image/png": "PNG",
    "image/webp": "WEBP",
    "image/avif": "AVIF",
    "image/gif": "GIF",
    "image/svg+xml": "SVG",
    "image/bmp": "BMP",
    "image/tiff": "TIFF",
    "image/x-icon": "ICO",
    "image/vnd.microsoft.icon": "ICO",
    "image/heic": "HEIC",
    "image/heif": "HEIF",
    "audio/mpeg": "MP3",
    "audio/mp3": "MP3",
    "audio/wav": "WAV",
    "audio/x-wav": "WAV",
    "audio/ogg": "OGG",
    "audio/mp4": "M4A",
    "audio/x-m4a": "M4A",
    "audio/aac": "AAC",
    "audio/flac": "FLAC",
    "audio/x-flac": "FLAC",
    "audio/opus": "OPUS",
    "audio/x-ms-wma": "WMA",
    "audio/amr": "AMR",
    "video/mp4": "MP4",
    "video/webm": "WEBM",
    "video/quicktime": "MOV",
    "video/x-msvideo": "AVI",
    "video/avi": "AVI",
    "video/x-matroska": "MKV",
    "video/x-m4v": "M4V",
    "video/m4v": "M4V",
    "video/mpeg": "MPEG",
    "video/3gpp": "3GP",
    "video/3gpp2": "3G2",
    "video/x-flv": "FLV",
    "video/x-ms-wmv": "WMV",
    "video/mp2t": "TS",
    "video/vnd.dlna.mpeg-tts": "M2TS",
    "video/ogg": "OGV",
  };

  return types[mimeType.toLowerCase()] ?? "OTHER";
};