import type { StoredFile } from "@/types/file";

export const mockFiles: StoredFile[] = [
  {
    id: "1",
    name: "Q3 product roadmap.pdf",
    type: "PDF",
    size: 2.8,
    sizeLabel: "2.8 MB",
    updatedAt: "12 min ago",
    owner: "You",
    visibility: "private",
    favorite: true,
    shared: true,
    recent: true,
  },
  {
    id: "2",
    name: "Brand guidelines 2026.pdf",
    type: "PDF",
    size: 8.4,
    sizeLabel: "8.4 MB",
    updatedAt: "Yesterday",
    owner: "Maya Chen",
    visibility: "public",
    favorite: true,
    shared: true,
    recent: true,
  },
  {
    id: "3",
    name: "Launch campaign assets.zip",
    type: "ZIP",
    size: 186,
    sizeLabel: "186 MB",
    updatedAt: "Aug 12, 2026",
    owner: "You",
    visibility: "private",
    favorite: false,
    shared: false,
    recent: true,
  },
  {
    id: "4",
    name: "Revenue forecast.xlsx",
    type: "XLSX",
    size: 1.3,
    sizeLabel: "1.3 MB",
    updatedAt: "Aug 10, 2026",
    owner: "You",
    visibility: "private",
    favorite: true,
    shared: false,
    recent: false,
  },
  {
    id: "5",
    name: "Product demo final.mp4",
    type: "MP4",
    size: 342,
    sizeLabel: "342 MB",
    updatedAt: "Aug 8, 2026",
    owner: "Noah Williams",
    visibility: "public",
    favorite: false,
    shared: true,
    recent: false,
  },
  {
    id: "6",
    name: "Offsite team photo.jpg",
    type: "JPG",
    size: 5.2,
    sizeLabel: "5.2 MB",
    updatedAt: "Aug 4, 2026",
    owner: "You",
    visibility: "public",
    favorite: false,
    shared: true,
    recent: false,
  },
  {
    id: "7",
    name: "Customer research notes.docx",
    type: "DOCX",
    size: 0.8,
    sizeLabel: "820 KB",
    updatedAt: "Jul 29, 2026",
    owner: "You",
    visibility: "private",
    favorite: false,
    shared: false,
    recent: false,
  },
];
